# control status type
int32 STAND_BY                  =  0
int32 CAPTURED                  =  1
int32 DISTURBED                 =  2
int32 KEEP_POSE                 = 10
int32 KEEPING_POSE_BY_COLLISION = 11
int32 STOP_MOVING               = 20
int32 MOVE_TO_RELATIVE_TARGET   = 30
int32 MOVE_TO_ABSOLUTE_TARGET   = 40
int32 RELEASE                   = 50
int32 DOCK                      = 60
int32 MOVING_TO_AIA_AIP         = 61
int32 WAITING_AT_AIA_AIP        = 62
int32 MOVING_TO_RDA_AIP         = 63
int32 MOVING_TO_RDP             = 64
int32 DOCKING_STAND_BY          = 65
int32 DOCK_WITHOUT_CORRECTION   = 69
int32 SCAN                      = 70

int32 type
